name: Automated E2E Testing

on:
  pull_request:
  workflow_dispatch:

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install project dependencies
        run: npm install

      - name: Run Cypress E2E tests
        uses: cypress-io/github-action@v4
        with:
          browser: electron
          cache-key: ${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}

      - name: Run Jest unit tests
        run: npm run test
