name: Automated E2E Testing

on:
  pull_request:
  workflow_dispatch:

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Cypress E2E tests
        uses: cypress-io/github-action@v4
        with:
          browser: electron
          cache-key: ${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}

      - name: Upload Cypress Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cypress-artifacts
          path: |
            cypress/videos/
            cypress/screenshots/
            cypress/logs/

